---
- name: Converge Root CA
  hosts: root_ca_servers
  become: true
  roles:
    - role: tolecnal.smallstep

- name: Converge Intermediate CA
  hosts: intermediate_ca_servers
  become: true
  roles:
    - role: tolecnal.smallstep

- name: Converge Clients
  hosts: web_servers
  become: true
  roles:
    - role: tolecnal.smallstep
